# Generated by Django 3.0 on 2020-01-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Essays',
        ),
    ]
