# Generated by Django 3.0 on 2020-01-04 15:24

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_auto_20200102_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
