# Generated by Django 3.0 on 2020-01-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0003_auto_20200104_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='content',
            field=models.TextField(),
        ),
    ]
