# Generated by Django 3.0 on 2020-01-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0004_auto_20200104_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='image',
            field=models.TextField(default='static'),
            preserve_default=False,
        ),
    ]
